if(MBED_DIR)
	set(REL_MBED_LOCATION ${MBED_DIR} "")
else()
	set(REL_MBED_LOCATION "mbed" CACHE INTERNAL "")
endif()

get_filename_component(REL_MBED_LOCATION ${REL_MBED_LOCATION} ABSOLUTE)
set(MBED_LOCATION ${REL_MBED_LOCATION} CACHE INTERNAL "")

if(NOT TOOLCHAIN_PREFIX)
    set(TOOLCHAIN_PREFIX "/usr")
    message(STATUS "No TOOLCHAIN_PREFIX specified, using default: " ${TOOLCHAIN_PREFIX})
endif()
if(NOT TARGET_TRIPLET)
    set(TARGET_TRIPLET "arm-none-eabi")
    message(STATUS "No TARGET_TRIPLET specified, using default: " ${TARGET_TRIPLET})
endif()

set(TOOLCHAIN_BIN_DIR ${TOOLCHAIN_PREFIX}/bin)
set(TOOLCHAIN_INC_DIR ${TOOLCHAIN_PREFIX}/${TARGET_TRIPLET}/include)
set(TOOLCHAIN_LIB_DIR ${TOOLCHAIN_PREFIX}/${TARGET_TRIPLET}/lib)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
	 
set(CMAKE_C_COMPILER ${TOOLCHAIN_BIN_DIR}/${TARGET_TRIPLET}-gcc CACHE INTERNAL "c compiler")
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BIN_DIR}/${TARGET_TRIPLET}-g++ CACHE INTERNAL "cxx compiler")
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_BIN_DIR}/${TARGET_TRIPLET}-gcc CACHE INTERNAL "asm compiler")

set(CMAKE_OBJCOPY ${TOOLCHAIN_BIN_DIR}/${TARGET_TRIPLET}-objcopy CACHE INTERNAL "objcopy")
set(CMAKE_OBJDUMP ${TOOLCHAIN_BIN_DIR}/${TARGET_TRIPLET}-objdump CACHE INTERNAL "objdump")

set(CMAKE_C_FLAGS
	"-fno-builtin -ffunction-sections -fdata-sections -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nosys.specs -D__CMSIS_RTOS -D__CORTEX_M4 -D__FPU_PRESENT=1 -D__MBED__=1 -D__MBED_CMSIS_RTOS_CM -DARM_MATH_CM4 -DDEVICE_ANALOGIN=1 -DDEVICE_ANALOGOUT=1 -DDEVICE_CAN=1 -DDEVICE_I2C=1 -DDEVICE_I2CSLAVE=1 -DDEVICE_INTERRUPTIN=1 -DDEVICE_PORTIN=1 -DDEVICE_PORTINOUT=1 -DDEVICE_PORTOUT=1 -DDEVICE_PWMOUT=1 -DDEVICE_RTC=1 -DDEVICE_SERIAL=1 -DDEVICE_SERIAL_FC=1 -DDEVICE_SLEEP=1 -DDEVICE_SPI=1 -DDEVICE_SPISLAVE=1 -DDEVICE_STDIO_MESSAGES=1 -DMBED_BUILD_TIMESTAMP=1474028085.65 -DTARGET_CORTEX_M -DTARGET_FF_ARDUINO -DTARGET_LIKE_CORTEX_M4 -DTARGET_LIKE_MBED -DTARGET_M4 -DTARGET_NUCLEO_L432KC -DTARGET_RELEASE -DTARGET_RTOS_M4_M7 -DTARGET_STM -DTARGET_STM32L4 -DTARGET_STM32L432KC -DTARGET_UVISOR_UNSUPPORTED -DTOOLCHAIN_GCC -DTOOLCHAIN_GCC_ARM -DTOOLCHAIN_object"
CACHE INTERNAL "")

set(CMAKE_C_FLAGS_DEBUG "-Og -g" CACHE INTERNAL "")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-Og -g" CACHE INTERNAL "")
set(CMAKE_C_FLAGS_RELEASE "-O3" CACHE INTERNAL "")
set(CMAKE_C_FLAGS_RELMINSIZE "-Os" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_DEBUG "-Og -g" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-Og -g" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_RELEASE "-O3" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_RELMINSIZE "-Os" CACHE INTERNAL "")

set(CMAKE_CXX_FLAGS
	"-fno-builtin -ffunction-sections -fdata-sections -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nosys.specs -D__CMSIS_RTOS -D__CORTEX_M4 -D__FPU_PRESENT=1 -D__MBED__=1 -D__MBED_CMSIS_RTOS_CM -DARM_MATH_CM4 -DDEVICE_ANALOGIN=1 -DDEVICE_ANALOGOUT=1 -DDEVICE_CAN=1 -DDEVICE_I2C=1 -DDEVICE_I2CSLAVE=1 -DDEVICE_INTERRUPTIN=1 -DDEVICE_PORTIN=1 -DDEVICE_PORTINOUT=1 -DDEVICE_PORTOUT=1 -DDEVICE_PWMOUT=1 -DDEVICE_RTC=1 -DDEVICE_SERIAL=1 -DDEVICE_SERIAL_FC=1 -DDEVICE_SLEEP=1 -DDEVICE_SPI=1 -DDEVICE_SPISLAVE=1 -DDEVICE_STDIO_MESSAGES=1 -DMBED_BUILD_TIMESTAMP=1474028085.65 -DTARGET_CORTEX_M -DTARGET_FF_ARDUINO -DTARGET_LIKE_CORTEX_M4 -DTARGET_LIKE_MBED -DTARGET_M4 -DTARGET_NUCLEO_L432KC -DTARGET_RELEASE -DTARGET_RTOS_M4_M7 -DTARGET_STM -DTARGET_STM32L4 -DTARGET_STM32L432KC -DTARGET_UVISOR_UNSUPPORTED -DTOOLCHAIN_GCC -DTOOLCHAIN_GCC_ARM -DTOOLCHAIN_object "
CACHE INTERNAL "")

set(LINKER_SCRIPT "${MBED_LOCATION}/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/STM32L432XX.ld")
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -T ${LINKER_SCRIPT}" CACHE INTERNAL "")
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}" CACHE INTERNAL "")

#set(CMAKE_FIND_ROOT_PATH "${REL_MBED_LOCATION};${REL_MBED_LOCATION}/TARGET_NUCLEO_L432KC/;${REL_MBED_LOCATION}/TARGET_NUCLEO_L432KC/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM" CACHE INTERNAL "")
